name 'docker001'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures docker001'
long_description 'Installs/Configures docker001'
version '0.14.0'

depends 'apt', '~>2.6.1'
depends 'docker', '=0.43.0'
